In [ ]:
#data encoding >> converting categorical columns into numeric
#Nominal/OHE
#label and ordinal encoding
#Target guided ordinal encoding

In [ ]:
#Nominal/OHE >> Binary vector for each of the categories
#example single, married, separated
#single: [1, 0, 0]
#married: [0, 1, 0]
#separated: [0, 0, 1]

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({"status": ["single", "married", "separated", "single", "married"]})

In [ ]:
df

status
0     single
1    married
2  separated
3     single
4    married

In [ ]:
encoder = OneHotEncoder()

In [ ]:
encoder

OneHotEncoder()

In [ ]:
encoded = encoder.fit_transform(df[["status"]]).toarray()

In [ ]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [ ]:
encoder_df = pd.DataFrame(encoded, columns = encoder.get_feature_names_out())

In [ ]:
encoder_df

status_married  status_separated  status_single
0             0.0               0.0            1.0
1             1.0               0.0            0.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0

In [ ]:
encoder.transform([["single"]]).toarray()

C:\Users\ajayk\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1.]])

In [ ]:
#h/w
#pd.get_dummies()

In [ ]:
pd.concat([df, encoder_df], axis = 1)

status  status_married  status_separated  status_single
0     single             0.0               0.0            1.0
1    married             1.0               0.0            0.0
2  separated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0

In [ ]:
import seaborn as sns
sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
#label encoding >> assign unique label to the categories
# using map or using library

In [ ]:
df

status
0     single
1    married
2  separated
3     single
4    married

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [ ]:
label_encoder.fit_transform(df[['status']])

C:\Users\ajayk\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [ ]:
label_encoder.transform([["separated"]])

C:\Users\ajayk\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([1])

In [ ]:
#ordinal encoding

#High school : 1
#gradiate: 2
#post graduate: 3
#Phd: 4

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"qualification": ["HS","GR", "PG", "PHD", "HS", "PHD"]})

In [ ]:
df

qualification
0            HS
1            GR
2            PG
3           PHD
4            HS
5           PHD

In [ ]:
encoder = OrdinalEncoder(categories=[["HS", "GR", "PG", "PHD"]])

In [ ]:
encoder.fit_transform(df[["qualification"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [0.],
       [3.]])

In [ ]:
#new data
encoder.transform([["PG"]])

C:\Users\ajayk\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[2.]])

In [ ]:
#Target guided ordinal encoding
#relationship with target variable
#A lot of unique categories
#replace the category with mean and median of respective group

In [ ]:
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})

In [ ]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [ ]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [ ]:
df["time_encoded"] = df['time'].map(mean_price)

In [ ]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333

In [ ]:
sns.load_dataset("tips")

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]